// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTC0KPoyzwoLjzIATRUsOItEeTb_Hqho',
    appId: '1:110801499436:web:0bd6c9e610d5cecd4e2889',
    messagingSenderId: '110801499436',
    projectId: 'major-cea82',
    authDomain: 'major-cea82.firebaseapp.com',
    storageBucket: 'major-cea82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKALKByWi5lALsQLblVcdb_DhqJ4ZX8eQ',
    appId: '1:110801499436:android:7e241a47a53bc72f4e2889',
    messagingSenderId: '110801499436',
    projectId: 'major-cea82',
    storageBucket: 'major-cea82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZq-hoOBTpRMPijKCNLnX5retQzpH_vTo',
    appId: '1:110801499436:ios:93a596696a0a7a9b4e2889',
    messagingSenderId: '110801499436',
    projectId: 'major-cea82',
    storageBucket: 'major-cea82.firebasestorage.app',
    androidClientId: '110801499436-0114qo5fj89ur6nece966j4nr0smc9b0.apps.googleusercontent.com',
    iosClientId: '110801499436-80f2na773rf1t9nfojetkoiu9dq46ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZq-hoOBTpRMPijKCNLnX5retQzpH_vTo',
    appId: '1:110801499436:ios:93a596696a0a7a9b4e2889',
    messagingSenderId: '110801499436',
    projectId: 'major-cea82',
    storageBucket: 'major-cea82.firebasestorage.app',
    androidClientId: '110801499436-0114qo5fj89ur6nece966j4nr0smc9b0.apps.googleusercontent.com',
    iosClientId: '110801499436-80f2na773rf1t9nfojetkoiu9dq46ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTTC0KPoyzwoLjzIATRUsOItEeTb_Hqho',
    appId: '1:110801499436:web:e74a2b07a08a35334e2889',
    messagingSenderId: '110801499436',
    projectId: 'major-cea82',
    authDomain: 'major-cea82.firebaseapp.com',
    storageBucket: 'major-cea82.firebasestorage.app',
  );
}
